language: objective-c
osx_image: xcode7.2
podfile: Example/Podfile
before_install:
  - gem uninstall cocoapods
  - gem install cocoapods --pre
  - pod install --project-directory=Example
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail && xcodebuild test -workspace Example/SwiftECP.xcworkspace -scheme SwiftECP-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' ONLY_ACTIVE_ARCH=NO |
    xcpretty -c
  - pod lib lint --quick
