language: objective-c
osx_image: xcode8.3
podfile: Example/Podfile
before_install:
  - brew update
  - brew install swiftlint
  - gem uninstall cocoapods
  - gem install cocoapods --pre
  - pod setup
  - pod install --project-directory=Example
install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - swiftlint
  - set -o pipefail && xcodebuild test -workspace Example/SwiftECP.xcworkspace -scheme SwiftECP-Example -destination 'platform=iOS Simulator,name=iPhone 6,OS=latest' -enableCodeCoverage YES ONLY_ACTIVE_ARCH=NO GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES |
    xcpretty -c
  - pod lib lint --quick --allow-warnings
after_success:
  - bash <(curl -s https://codecov.io/bash)
